apiVersion: v1
kind: Service
metadata:
  name: okteto-teet111
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okteto-teet111"
    port: 8080
  selector:
    app: okteto-teet111
